# Generated by Django 4.2.4 on 2023-08-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchmen',
            new_name='Watchman',
        ),
    ]
