# Generated by Django 4.2.4 on 2023-09-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_watchmen_watchman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='c_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='m_image',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='n_image',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='v_image',
        ),
        migrations.RemoveField(
            model_name='watchman',
            name='w_image',
        ),
    ]
