# Generated by Django 4.2.4 on 2023-09-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member_m_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='m_image',
        ),
    ]
