# Generated by Django 4.2.4 on 2023-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_chairman_c_image_remove_event_e_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
