# Generated by Django 4.2.4 on 2023-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_member_m_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.CharField(max_length=100),
        ),
    ]
